platform:
- x64
environment:
  nodejs_version: "10"
  GITHUB_TOKEN:
    secure: UAWP+sQRK/cwf+zm45J2nJdQ50HWFHL14jnjWN/bc2nqZbU9RDq1yiLF+mM7RaSo
cache:
- '%APPDATA%\npm-cache'
- '%USERPROFILE%\.electron'
skip_non_tags: true
artifacts:
- path: 'packages\altair-electron\out\make\**\*'
  name: altairAll

- path: 'packages\altair-electron\out\altair-win32-x64\altair.exe'
  name: altairWin

- path: 'packages\altair-electron\out\make\**/*.exe'
  name: altairExe

- path: 'packages\altair-electron\out\make\**/*.nupkg'
  name: altairNuget

install:
- ps: Install-Product node $env:nodejs_version $env:platform
- set PATH=%APPDATA%\npm;%PATH%
# - npm install
- yarn

before_test:
# - yarn global add @angular/cli@1.6.3
- yarn global add karma
# - yarn global add electron-forge
- yarn
# - npm install -g @angular/cli
# - npm install -g karma
# - npm install -g electron-forge
# - npm install
- yarn lerna bootstrap
- yarn build-app

test_script:
- node --version
# - npm --version
# - npm run test-build
- yarn --version
- yarn lerna run --scope altair-app test --stream

build: off # We do not intend to build using MS Build

# Run build in after_test to generate artifacts
after_test:
# - ps: (Get-Content .\dist\index.html) | ForEach-Object { $_ -replace '<base href="/">', '<base href="./">' } | Set-Content .\dist\index.html
# - npm run make
- yarn build-electron
# - npm run dist-electron

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: UAWP+sQRK/cwf+zm45J2nJdQ50HWFHL14jnjWN/bc2nqZbU9RDq1yiLF+mM7RaSo
  artifact: altairAll, altairWin
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
