platform:
- x64
environment:
  nodejs_version: "6"
  GITHUB_TOKEN:
    secure: UAWP+sQRK/cwf+zm45J2nJdQ50HWFHL14jnjWN/bc2nqZbU9RDq1yiLF+mM7RaSo
cache:
- '%APPDATA%\npm-cache'
- '%USERPROFILE%\.electron'
skip_non_tags: true
artifacts:
- path: 'out\make\**\*'
  name: altairAll

- path: 'out\altair-win32-x64\altair.exe'
  name: altairWin

- path: 'out\make\**/*.exe'
  name: altairExe

- path: 'out\make\**/*.nupkg'
  name: altairNuget

install:
- ps: Install-Product node $env:nodejs_version $env:platform
- set PATH=%APPDATA%\npm;%PATH%
- npm install

before_test:
- npm install -g @angular/cli
- npm install -g karma
- npm install -g electron-forge
- npm install
- ng build

test_script:
- node --version
- npm --version
- npm run test-build

build: off # We do not intend to build using MS Build

# Run build in after_test to generate artifacts
after_test:
- ps: (Get-Content .\dist\index.html) | ForEach-Object { $_ -replace '<base href="/">', '<base href="./">' } | Set-Content .\dist\index.html
- npm run make
- npm run dist-electron

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: UAWP+sQRK/cwf+zm45J2nJdQ50HWFHL14jnjWN/bc2nqZbU9RDq1yiLF+mM7RaSo
  artifact: altairAll, altairWin
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
