sudo: required
dist: trusty
language: node_js
cache: yarn
os:
- linux
- osx
node_js:
- 10
env:
- DEBUG=electron-forge:*
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - google-chrome-beta
    - fakeroot
    - rpm
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
before_script:
- yarn global add @angular/cli karma electron-forge lerna
- yarn
- yarn build
- echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc
script:
- ng lint
- if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then yarn test-single-run; fi
- if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then ng e2e; fi
- if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then yarn test-electron; fi
- if [ ! -z "$TRAVIS_TAG" ]; then yarn build-electron; fi
- if [[ "$TRAVIS_OS_NAME" = "linux" ]]; then yarn build; fi # Need to generate files for deployment
before_deploy:
deploy:
- provider: releases
  api_key:
    secure: Raef82s/PIkWThnr5vxHsxZX7FI6LKB3dbUkHzEs/S88hhibQCLuUIrvtbPwEJ/nxj0tpnD93elRQWpYsFRa38omv11g0o5eSUy7WwEHEum6g6se1fH3DqhBJsnIJFtfNXwdysMuvzWeJQ4P4j37jSg3wuCs9oJn0I+GrtS/wrE8EyxGKjtd68lVZo5rNCllUiHeizl8oIcRTUREKexxpsLEapBqgxmkFDn7lbgLDgt4/VwtaCZVN6bAnjknJS9DMynOJS0S1uyl6Gqd1paHVvEPrJv/UpeGKsp+OyoU7qbt/0ZXqXd1Yyym5jp0NAdb2IVNUAiyAAMUjy0qYDIZJMLAOhoO/GlJjvr+Sun81Fgv3fTDPzdUkHLUOVAFqsAmqhkupdZ3PnbiPExk3M3vTIEYI6v2CdxEglZyuZ1GNZ1551CT2hddHuoGue3JGaeq/V8n7QGZUGdplw9NHr7YOkuGpbbxGDjJM/RQXXEdAj1YXTSe225NNEOjoY5AuaVnIW76pfzhjEZtAHCpiYDfqECjtQ9dNuV5K58qElfPmDlBjYv1/G46OiEb/wpFiXtNZel+pvYaV7EK0RNA5IYSUn/S5v2MHEd8XVS90KV2L+CFv++9M46le3Nx6Qr4Lbu7VeY3va7JA/FCN+6HWpoupCg4N98rNOgfjay6FO/d56c=
  file_glob: true
  file:
    - out/make/*
  skip_cleanup: true
  on:
    tags: true
- provider: firebase
  token:
    secure: tgWQ77WjL/iWxY4mFmRsWG/w/Sk+szRVu99ynuT5Vjz7rSHkHsKhTrowTMAS7DV3Iq4yvSuVt2bPbiCYhANAiVixddA20BvoF5ZjGsafi5MXh0LPCrCXxbmsFmhp7MuQ5n94E800slGghtmRVPAwh1dlP/kpInwfqUY7RMcEQF+KFU/LVcec5hriCaDm1G4RQmaD6ZvkqUSTR0rqAh8fhPa/XXASrOdGOvU4O8oxOGP41ozF5n61KqYgWxst9Dwb/G0y7fZ1pomi30lAGWg5LodwHWOnkiOmN+bD0xDM9/D8OFAx9i/Afp1PnuGCA9EE0eI+oelnyZ4MSKPmgl20k6jrHpPgSziw2oKS8ceVYMa9dGHovVSmUmmBie93zBXF3mCf9zsv4WM7ekC9vv6C/P4K4MGeFSDIDscxbb7RYVaYto9UJMYDBz27dEsejSU4183fhKUS9KxnhVR0kZ/G45lPkORkDzdMPVMrRz6S1aL/fwMiNNjCsMWvVc5JDfozsIopiiAAtKbRp3apgxySktWkojfndX0BASyLyeSCG3p7enP/40OG7ikyDxMwxcVHZp9HMCnPxTkhdPAH2Dje1dweoWh6/sw8/7kjw2+X1WxuV1N5Wu9nB+vI7T6EMgxJZjTfN1fXSOGiKb/CVIDLb3jCpRJ/PIInXwsI43I+umY=
  message: Deploying to firebase.
  skip_cleanup: true
  on:
    branch: master
- provider: surge
  project: ./dist
  domain: altair-gql-translate.surge.sh
  skip_cleanup: true
  on:
    branch: staging
- provider: script
  script: sh bin/publish_packages.sh
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
- provider: snap
  file_glob: true
  snap: out/**/*.snap
  channel: stable
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
