name: Release (experimental extras)

on:
  workflow_run:
    workflows: [Release]
    types:
    - completed
  workflow_dispatch:


permissions:
  contents: write

jobs:
  deploy-docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn build-docs
        env:
          GITHUB_TOKEN: ${{ github.token }}
      # https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration/#use-github-actions
      - name: Publish to cloudflare pages âœ¨
        uses: cloudflare/pages-action@1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: altair-site
          directory: site/src/.vuepress/dist
          gitHubToken: ${{ github.token }}
  # deploy-docs:
  #   name: Deploy docs
  #   runs-on: ubuntu-latest
  #   # if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #   steps:
  #     - uses: actions/checkout@v2.3.1
  #     - name: Use Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 16
  #     - run: yarn build-docs
  #       env:
  #         GITHUB_TOKEN: ${{ github.token }}
  #     - name: Deploy to github pages ðŸš€
  #       uses: JamesIves/github-pages-deploy-action@4.1.6
  #       with:
  #         branch: gh-pages # The branch the action should deploy to.
  #         folder: site/src/.vuepress/dist # The folder the action should deploy.
  extension-publish:
    name: Publish firefox addon
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - run: yarn
    - run: yarn build-ext
    - uses: trmcnvn/firefox-addon@v1
      with:
        uuid: '{c336a627-bbea-4dbb-aa77-83899b52149a}'
        xpi: extension-builds/mozilla-build/build.zip
        manifest: extension-builds/mozilla-files/manifest.json
        api-key: ${{ secrets.FIREFOX_API_KEY }}
        api-secret: ${{ secrets.FIREFOX_API_SECRET }}
    - uses: trmcnvn/chrome-addon@v2
      with:
        refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
        client-id: ${{ secrets.CHROME_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        zip: extension-builds/chrome-build/build.zip
        extension: flnheeellpciglgpaodhkhmapeljopja
  chrome-extension-upload:
    name: Publish webextension
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Build extensions
      run: |
        yarn
        yarn lerna bootstrap
        yarn build-ext
    - name: Upload & release
      uses: mnao305/chrome-extension-upload@1.1.1
      with:
        file-path: extension-builds/chrome-build/build.zip
        extension-id: flnheeellpciglgpaodhkhmapeljopja
        client-id: ${{ secrets.CHROME_CLIENT_ID }}
        client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
        refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
  # TODO: Publish browser extensions (mozilla, edge)
  # https://github.com/fregante/web-ext-submit
