name: release-extra-experimental

on:
  workflow_run:
    workflows: [release-workflow]
    types:
      - completed
  workflow_dispatch:

env:
  NODE_VERSION: 22
  # NODE_OPTIONS: --openssl-legacy-provider

permissions: {}

jobs:
  deploy-docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - run: pnpm install
        env:
          GITHUB_TOKEN: ${{ github.token }}
      # https://developers.cloudflare.com/pages/how-to/use-direct-upload-with-continuous-integration/#use-github-actions
      - name: Publish to cloudflare pages âœ¨
        uses: cloudflare/pages-action@f0a1cd58cd66095dee69bfa18fa5efd1dde93bca # v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: altair-site
          directory: packages/altair-docs/.vitepress/dist
          gitHubToken: ${{ github.token }}
  # deploy-docs:
  #   name: Deploy docs
  #   runs-on: ubuntu-latest
  #   # if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #   steps:
  #     - uses: actions/checkout@v2.3.1
  #     - name: Use Node.js
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 16
  #     - run: pnpm install
  #       env:
  #         GITHUB_TOKEN: ${{ github.token }}
  #     - name: Deploy to github pages ðŸš€
  #       uses: JamesIves/github-pages-deploy-action@4.1.6
  #       with:
  #         branch: gh-pages # The branch the action should deploy to.
  #         folder: packages/altair-docs/.vitepress/dist # The folder the action should deploy.
  extension-publish:
    name: Publish firefox addon
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - name: Use Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build-ext
      - uses: trmcnvn/firefox-addon@0d05671269b82c69c3f22ed86d8e772e89d47cf4 # v1
        continue-on-error: true
        with:
          uuid: "{c336a627-bbea-4dbb-aa77-83899b52149a}"
          xpi: packages/altair-crx/altair.zip
          manifest: packages/altair-crx/dist/manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
      - uses: wdzeng/edge-addon@v1
        continue-on-error: true
        with:
          product-id: f725e625-c035-444d-b373-fba0e41855c1
          zip-path: packages/altair-crx/altair.zip
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
          client-secret: ${{ secrets.EDGE_CLIENT_SECRET }}
          access-token-url: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}
      - uses: wdzeng/chrome-extension@v1
        continue-on-error: true
        with:
          extension-id: flnheeellpciglgpaodhkhmapeljopja
          zip-path: packages/altair-crx/altair.zip
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
      - uses: trmcnvn/chrome-addon@v2
        continue-on-error: true
        with:
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          zip: packages/altair-crx/altair.zip
          extension: flnheeellpciglgpaodhkhmapeljopja
  chrome-extension-upload:
    name: Publish webextension
    runs-on: ubuntu-latest
    continue-on-error: true
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - name: Build extensions
        run: |
          pnpm install
          pnpm build:ci
          pnpm build-ext
      - name: Upload & release
        uses: mnao305/chrome-extension-upload@1.1.1
        with:
          file-path: packages/altair-crx/altair.zip
          extension-id: flnheeellpciglgpaodhkhmapeljopja
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
  # TODO: Publish browser extensions (mozilla, edge)
  # https://github.com/fregante/web-ext-submit
